version: '3.8'

services:
  hunter_worker:
    build:
      context: ./hunter
      dockerfile: Dockerfile
    command: poetry run celery -A hunter.celery_app worker --loglevel=info
    volumes:
      - ./hunter:/app
    depends_on:
      - rabbitmq
      - redis
    env_file:
      - .env

  hunter_beat:
    build:
      context: ./hunter
      dockerfile: Dockerfile
    command: poetry run celery -A hunter.celery_app beat --loglevel=info
    volumes:
      - ./hunter:/app
    depends_on:
      - rabbitmq
      - redis
    env_file:
      - .env

  pricer:
    build:
      context: ./pricer
      dockerfile: Dockerfile
    command: poetry run celery -A pricer.celery_app worker --loglevel=info
    volumes:
      - ./pricer:/app
    depends_on:
      - rabbitmq
      - redis
    env_file:
      - .env

  writer:
    build:
      context: ./writer
      dockerfile: Dockerfile
    command: poetry run celery -A writer.celery_app worker --loglevel=info
    volumes:
      - ./writer:/app
    depends_on:
      - rabbitmq
      - redis
      - mongo
    env_file:
      - .env

  matcher:
    build:
      context: ./matcher
      dockerfile: Dockerfile
    command: poetry run python matcher/main.py
    volumes:
      - ./matcher:/app
    depends_on:
      - rabbitmq
      - redis
      - mongo-init-replica
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js

  mongo-init-replica:
    image: mongo:latest
    depends_on:
      - mongo
    entrypoint: >
      bash -c "
      echo 'Waiting for MongoDB to start...' &&
      sleep 30 &&
      until mongosh --host mongo --eval 'print(\"waited for connection\")'; do sleep 2; done &&
      mongosh --host mongo --eval 'rs.initiate({_id: \"rs0\", members: [{_id: 0, host: \"mongo:27017\"}]})' &&
      sleep 5 &&
      echo 'Replica set initiated'
      "
