"""notification_endpoint

Revision ID: 07e5a41dea71
Revises: 9bfb09604473
Create Date: 2024-11-03 23:40:33.735642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "07e5a41dea71"
down_revision: Union[str, None] = "9bfb09604473"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions", sa.Column("notification_endpoint", sa.String(), nullable=False)
    )
    op.drop_column("subscriptions", "user_email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions",
        sa.Column("user_email", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("subscriptions", "notification_endpoint")
    # ### end Alembic commands ###
