"""removed floor_level

Revision ID: a02b40ec0805
Revises: f31fbb0e98c4
Create Date: 2024-09-19 21:53:44.087841

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a02b40ec0805"
down_revision: Union[str, None] = "f31fbb0e98c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subscriptions",
        "bedrooms",
        existing_type=postgresql.ARRAY(sa.INTEGER()),
        type_=sa.ARRAY(sa.String()),
        existing_nullable=True,
    )
    op.drop_column("subscriptions", "floor_level")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions",
        sa.Column(
            "floor_level",
            postgresql.ARRAY(sa.INTEGER()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "subscriptions",
        "bedrooms",
        existing_type=sa.ARRAY(sa.String()),
        type_=postgresql.ARRAY(sa.INTEGER()),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
