"""Initial

Revision ID: c91c0be77dd2
Revises: 
Create Date: 2024-06-23 22:06:02.006493

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c91c0be77dd2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription",
        sa.Column("website", sa.String(length=30), nullable=False),
        sa.Column("city", sa.String(length=30), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("subcategory", sa.String(length=30), nullable=False),
        sa.Column("development_type", sa.String(length=30), nullable=False),
        sa.Column("room_count", sa.String(length=30), nullable=False),
        sa.Column("minimum_price", sa.Integer(), nullable=False),
        sa.Column("maximum_price", sa.Integer(), nullable=False),
        sa.Column("minimum_area", sa.Integer(), nullable=False),
        sa.Column("maximum_area", sa.Integer(), nullable=False),
        sa.Column("floor_level", sa.String(length=30), nullable=False),
        sa.Column("furnishing", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subscription_id"), "subscription", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscription_id"), table_name="subscription")
    op.drop_table("subscription")
    # ### end Alembic commands ###
