"""“Initial”

Revision ID: e7fa21242085
Revises:
Create Date: 2024-07-31 22:13:55.553888

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7fa21242085"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription",
        sa.Column("city", sa.String(length=30), nullable=False),
        sa.Column("district", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("minimum_price", sa.Integer(), nullable=True),
        sa.Column("maximum_price", sa.Integer(), nullable=True),
        sa.Column("minimum_area", sa.Integer(), nullable=True),
        sa.Column("maximum_area", sa.Integer(), nullable=True),
        sa.Column("deposit", sa.Integer(), nullable=True),
        sa.Column("building_type", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("number_of_rooms", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("floor_level", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("is_furnished", sa.Boolean(), nullable=True),
        sa.Column("is_private_offer", sa.Boolean(), nullable=True),
        sa.Column("bedrooms", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("standard", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subscription_id"), "subscription", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscription_id"), table_name="subscription")
    op.drop_table("subscription")
    # ### end Alembic commands ###
