"""“destination”

Revision ID: e8286d157d21
Revises: e7fa21242085
Create Date: 2024-07-31 22:24:13.446145

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8286d157d21"
down_revision: Union[str, None] = "e7fa21242085"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscription",
        sa.Column("notification_destination", sa.String(), nullable=False),
    )
    op.add_column("subscription", sa.Column("user_email", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscription", "user_email")
    op.drop_column("subscription", "notification_destination")
    # ### end Alembic commands ###
