"""“User”

Revision ID: f31fbb0e98c4
Revises: e8286d157d21
Create Date: 2024-08-16 18:16:30.392222

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f31fbb0e98c4"
down_revision: Union[str, None] = "e8286d157d21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("subscription_limit", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=True)
    op.create_table(
        "subscriptions",
        sa.Column("notification_destination", sa.String(), nullable=False),
        sa.Column("user_email", sa.String(), nullable=False),
        sa.Column("city", sa.String(length=30), nullable=False),
        sa.Column("district", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("minimum_price", sa.Integer(), nullable=True),
        sa.Column("maximum_price", sa.Integer(), nullable=True),
        sa.Column("minimum_area", sa.Integer(), nullable=True),
        sa.Column("maximum_area", sa.Integer(), nullable=True),
        sa.Column("deposit", sa.Integer(), nullable=True),
        sa.Column("building_type", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("number_of_rooms", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("floor_level", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("is_furnished", sa.Boolean(), nullable=True),
        sa.Column("is_private_offer", sa.Boolean(), nullable=True),
        sa.Column("bedrooms", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("standard", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subscriptions_id"), "subscriptions", ["id"], unique=True)
    op.drop_index("ix_subscription_id", table_name="subscription")
    op.drop_table("subscription")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription",
        sa.Column("city", sa.VARCHAR(length=30), autoincrement=False, nullable=False),
        sa.Column(
            "district",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("minimum_price", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("maximum_price", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("minimum_area", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("maximum_area", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("deposit", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "building_type",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "number_of_rooms",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "floor_level",
            postgresql.ARRAY(sa.INTEGER()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("is_furnished", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_private_offer", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "bedrooms",
            postgresql.ARRAY(sa.INTEGER()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "standard",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "notification_destination",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="subscription_pkey"),
    )
    op.create_index("ix_subscription_id", "subscription", ["id"], unique=True)
    op.drop_index(op.f("ix_subscriptions_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
