version: '3.8'

services:
  worker:
    build: .
    command: celery -A hunter.celery_app worker --loglevel=info
    depends_on:
      - redis
      - rabbitmq
    environment:
      - PYTHONPATH=/app
    networks:
      - hunter_network

  beat:
    build: .
    command: celery -A hunter.celery_app beat --loglevel=info
    depends_on:
      - redis
      - rabbitmq
    environment:
      - PYTHONPATH=/app
    networks:
      - hunter_network

  redis:
    image: "redis:alpine"
    networks:
      - hunter_network

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - hunter_network

networks:
  hunter_network:
    driver: bridge